config/routes.rb
Rails.application.routes.draw do
  devise_for :users, ActiveAdmin::Devise.config
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'page/contact'
  post 'page/contact' => 'page#send_feedback', as: :send_feedback
  post 'page/online_applic' => 'page#send_online_app', as: :send_online_app
  get 'page/help_transport'
  get 'page/object'
  get 'page/online_applic'
  get 'page/photo_object_cotel'
  get 'page/photo_object_optica'
  get 'page/photo_object_sochi'
  get 'page/photo_object_transformer'
  get 'page/photo_object_apteki'
  get 'page/photo_object_svinkomplex'
  get 'page/photo_object_hlebzavod'
  get 'page/photo_object_agrotechnopark'
  get 'page/photo_object_svobodnaya'
  get 'page/reference'
  get 'page/sro'
  get 'page/technolog_park'
  get 'page/create_app'
  get 'page/create_message'

  root 'page#index'
end

app/models/admin_user.rb
# == Schema Information
#
# Table name: admin_users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime
#  updated_at             :datetime
#

class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/building.rb
# == Schema Information
#
# Table name: buildings
#
#  id         :integer          not null, primary key
#  name       :string
#  image      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Building < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  has_many :photos, dependent: :destroy

  validates :name, :image, presence: true
end

app/models/consult_request.rb
# == Schema Information
#
# Table name: consult_requests
#
#  id          :integer          not null, primary key
#  name        :string
#  contact     :string
#  place       :text
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class ConsultRequest < ActiveRecord::Base
	validates :name, :contact, :place, :description, presence: true
end

app/models/photo.rb
# == Schema Information
#
# Table name: photos
#
#  id         :integer          not null, primary key
#  image      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  special    :string
#  img        :string
#

class Photo < ActiveRecord::Base
	belongs_to :building
	validates :image, :special, presence: true

	mount_uploader :image, ImgUploader
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime
#  updated_at             :datetime
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def send_feedback
    UserMailer.feedback(params[:name], params[:contact],params[:message]).deliver_now
    redirect_to page_create_message_path
  end

  def send_online_app
    @consult_request = ConsultRequest.new(consult_request_params)
    respond_to do |format|
    	if @consult_request.save
    		format.html {redirect_to page_create_app_url}
        UserMailer.online_app(params[:name], params[:contact], params[:place], params[:description]).deliver_now
    	else
        format.html {redirect_to page_online_applic_url, notice: 'Не все поля были заполнены!'}
      end
    end
  end

  private
  def consult_request_params
  	params.permit(:name, :contact, :place, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def set_title(page_title)
    content_for(:title) { page_title }
  end
    
  def set_body_class(page_body)
    content_for(:body_class) { page_body }
  end

  def image_for_light_box(image)
    link_to image_tag(image, class: 'example-image'), image_url(image), class: 'example-image-link', data: { lightbox: 'example-set1' }
  end

  def images_list_for_photo_object(range)
    range.collect do |indx|
      content_tag :div, class: 'col-xs-4 tech_bl_new' do
        image_for_light_box("img_object_#{indx}.jpg")
      end
    end.join.html_safe
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><%= content_for?(:title) ? content_for(:title) + " - " : "" %> ООО “Тамбовстройсервис”</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
</head>
<body class='<%= content_for?(:body_class) ? content_for(:body_class) : "" %>'>
<!— Yandex.Metrika counter —>
<script type="text/javascript">
  (function (d, w, c) {
    (w[c] = w[c] || []).push(function() {
      try {
        w.yaCounter29119180 = new Ya.Metrika({id:29119180,
        webvisor:true,
        clickmap:true,
        trackLinks:true,
        accurateTrackBounce:true});
        } catch(e) { }
    });

    var n = d.getElementsByTagName("script")[0],
    s = d.createElement("script"),
    f = function () { n.parentNode.insertBefore(s, n); };
    s.type = "text/javascript";
    s.async = true;
    s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

    if (w.opera == "[object Opera]") {
      d.addEventListener("DOMContentLoaded", f, false);
    } else { f(); }
  })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="//mc.yandex.ru/watch/29119180" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!— /Yandex.Metrika counter —>
<header>
  <div class="container header">
    <div class="row">
      <div class="col-xs-3 col-xs-offset-2 txt_header"></div>
      <div class="col-xs-4 col-xs-offset-3 logo_bl">
        <a href="/"><%= image_tag 'logo.png' %></a>
        <div class="number_header">
          <p>+7 4752 531-271</p>
        </div>
      </div>
    </div>
    <div class="row">
      <nav>
        <ul class="navbar-nav navbar-right">
          <li class="<%= 'active' if action_name == "index" %>"><%= link_to 'О компании', root_path %>
          <li class="<%= 'active' if action_name == "object" || action_name == "photo_object_cotel" || 
            action_name == "photo_object_optica" || action_name == "photo_object_sochi" ||
            action_name == "photo_object_transformer" || action_name == "photo_object_apteki" %>">
            <%= link_to 'Фото объектов', page_object_path %>
          <li class="<%= 'active' if action_name == "technolog_park" %>"><%= link_to 'Парк техники', page_technolog_park_path %>
          <li class="<%= 'active' if action_name == "online_applic" %>"><%= link_to 'Онлайн заявки', page_online_applic_path %>
        </ul>
        <ul class="navbar-nav navbar-right">
          <li class="<%= 'active' if action_name == "sro" %>"><%= link_to 'Сро', page_sro_path %>
          <li class="<%= 'active' if action_name == "help_transport" %>"><%= link_to 'Справочная информация', page_help_transport_path %>
          <li class="<%= 'active' if action_name == "contact" %>"><%= link_to 'Контакты', page_contact_path %>
        </ul>
      </nav>
    </div>
  </div>
</header>
<content>
  <div class="container">
    <div class="row">
      <div class="col-xs-3 left_nav">
        <nav>
          <ul class="">
            <% if %w(photo_object_cotel photo_object_optica photo_object_sochi photo_object_transformer
             photo_object_apteki photo_object_svinkomplex photo_object_hlebzavod photo_object_agrotechnopark
             photo_object_svobodnaya).include? action_name %>
            <li class="active"><%= link_to 'Фото объектов', page_object_path %>
              <ul class="">
                <li class="<%= 'active' if action_name == "photo_object_cotel" %>">
                  <%= link_to 'Реконструкция котельной по адресу: г. Тамбов, ул. Бастионная, 23', page_photo_object_cotel_path %>
                </li>
                <li class="<%= 'active' if action_name == "photo_object_optica" %>">
                  <%= link_to 'Внутренние отделочные работы и устройство крыльца в торговом помещении магазина
                  «Оптика» по адресу: г. Тамбов, бульвар Энтузиастов, д. 41, кв. 81', page_photo_object_optica_path %>
                </li>
                <li class="<%= 'active' if action_name == "photo_object_sochi" %>">
                  <%= link_to 'Устройство парапета чаши фонтана "Сочи"
                  по адресу: г.Тамбов, Кронштадская площадь', page_photo_object_sochi_path %>
                </li>
                <li class="<%= 'active' if action_name == "photo_object_transformer" %>">
                  <%= link_to 'Общестроительные работы на объекте:
                  "Распределительная трансформаторная подстанция 0,4 кВ
                  с двумя трансформаторами мощностью 1000 кВа"', page_photo_object_transformer_path %>
                </li>
                <li class="<%= 'active' if action_name == "photo_object_apteki" %>">
                  <%= link_to 'Сеть аптек в Тамбовской области', page_photo_object_apteki_path %>
                </li>
                <li class="<%= 'active' if action_name == "photo_object_svinkomplex" %>">
                  <%= link_to 'Свиноводческий комплекс в Рассказовском районе', page_photo_object_svinkomplex_path %>
                </li>
                <li class="<%= 'active' if action_name == "photo_object_hlebzavod" %>">
                  <%= link_to 'Реконструкция покрытия хлебозавода в г. Рассказово', page_photo_object_hlebzavod_path %>
                </li>
                <li class="<%= 'active' if action_name == "photo_object_agrotechnopark" %>">
                  <%= link_to 'Коттеджный поселок в агротехнопарке "Мичуринский"', page_photo_object_agrotechnopark_path %>
                </li>
                <li class="<%= 'active' if action_name == "photo_object_svobodnaya" %>">
                  <%= link_to '9-этажный жилой дом по адресу г.Тамбов,ул.Свободная,4', page_photo_object_svobodnaya_path %>
                </li>
              </ul>
            </li>
            <% else %>
              <li class="<%= 'active' if action_name == "index" %>"><%= link_to 'О компании', root_path %>
              <li class="<%= 'active' if action_name == "object" %>"><%= link_to 'Фото объектов', page_object_path %>
              <li class="<%= 'active' if action_name == "technolog_park" %>"><%= link_to 'Парк техники', page_technolog_park_path %>
              <li class="<%= 'active' if action_name == "online_applic" %>"><%= link_to 'Онлайн заявки', page_online_applic_path %>
              <li class="<%= 'active' if action_name == "sro" %>"><%= link_to 'Сро', page_sro_path %>
              <li class="<%= 'active' if action_name == "help_transport" %>"><%= link_to 'Справочная информация', page_help_transport_path %>
              <li class="<%= 'active' if action_name == "contact" %>"><%= link_to 'Контакты', page_contact_path %>
            <% end %>
          </ul>
          <% if %w(photo_object_cotel photo_object_optica photo_object_sochi photo_object_transformer
            photo_object_apteki photo_object_svinkomplex photo_object_hlebzavod photo_object_agrotechnopark
            photo_object_svobodnaya).include? action_name %>
            <div class="new">
              <a href="http://cbr.ru//" target="_blank">
                <img src="http://bhom.ru/currencies/informer/1-61/" width="88" height="61" alt="Курс валют" title="Курс валют" border="0"/>
              </a><br><br>
              <table cellpadding=0 cellspacing=0 width=200 style="border:solid 1px #20b0fe;font-family:Times New Roman;font-size:12px;background-color:#edece9">
                <tr>
                  <td>
                    <table width=100% cellpadding=0 cellspacing=0>
                      <tr>
                        <td width=8 height=30 background="http://rp5.ru/informer/htmlinfa/topshl.png"  bgcolor=#20b0fe> </td>
                        <td width=* align=center background="http://rp5.ru/informer/htmlinfa/topsh.png" bgcolor=#20b0fe>
                          <a style="color:#ffffff; font-family:Times New Roman;font-size: 12px;" href="http://rp5.ru/8012/ru" target="_blank">
                            <b>Тамбов</b>
                          </a>
                        </td>
                        <td width=8 height=30 background="http://rp5.ru/informer/htmlinfa/topshr.png" bgcolor=#20b0fe> </td>
                      </tr>
                    </table>
                  </td>
                </tr>
                <tr>
                  <td valign=top style="padding:0;">
                    <iframe src="http://rp5.ru/htmla.php?id=8012&lang=ru&um=00000&bg=%23edece9&ft=%23ffffff&fc=%2320b0fe
                      &c=%23000000&f=Times New Roman&s=12&sc=2" width=100% height=150 frameborder=0 scrolling=no style="margin:0;">
                    </iframe>
                  </td>
                </tr>
              </table><br>
            </div>
            <% else %>
              <div class="new_2">
                <a href="http://cbr.ru//">
                  <img src="http://bhom.ru/currencies/informer/1-61/" width="88" height="61" alt="Курс валют" title="Курс валют" border="0"/>
                </a><br><br>
                <table cellpadding=0 cellspacing=0 width=200 style="border:solid 1px #20b0fe;font-family:Times New Roman;font-size:12px;background-color:#edece9">
                  <tr>
                    <td>
                      <table width=100% cellpadding=0 cellspacing=0>
                        <tr>
                          <td width=8 height=30 background="http://rp5.ru/informer/htmlinfa/topshl.png"  bgcolor=#20b0fe> </td>
                          <td width=* align=center background="http://rp5.ru/informer/htmlinfa/topsh.png" bgcolor=#20b0fe>
                            <a style="color:#ffffff; font-family:Times New Roman;font-size: 12px;" href="http://rp5.ru/8012/ru">
                              <b>Тамбов</b>
                            </a>
                          </td>
                          <td width=8 height=30 background="http://rp5.ru/informer/htmlinfa/topshr.png" bgcolor=#20b0fe> </td>
                        </tr>
                      </table>
                    </td>
                  </tr>
                  <tr>
                    <td valign=top style="padding:0;">
                      <iframe src="http://rp5.ru/htmla.php?id=8012&lang=ru&um=00000&bg=%23edece9&ft=%23ffffff&fc=%2320b0fe&c=%23000000&f=Times New  Romans=12&sc=2" width=100% height=150 frameborder=0 scrolling=no style="margin:0;"></iframe>
                    </td>
                  </tr>
                </table>
              </div>
            <% end %>
          </nav>
        </div>
      <%= yield %>
    </div>
  </div>
</content>
</body>
<br><br>
<footer>
  <div class="container">
    <div class="row">
      <div class="col-xs-4">
        <p>© ООО “Тамбовстройсервис”</p>
      </div>
      <div class="col-xs-11">
        <p>Адрес: 392000, г. Тамбов, ул. Советская, д. 206</p>
        <p>Тел./факс: +7 4752 531-271</p>
        <p>E-mail: <a href="mailto:tss68@mail.ru"> tss68@mail.ru</a></p>
      </div>
      <div class="col-xs-13">
        <br>
        <p>Разработано в <a href="http://www.online-lab.ru" target="_blank">Лаборатории</a></p>
      </div>
    </div>
  </div>
</footer>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
</body>
</html>

app/views/page/create_app.html.erb
<div class="col-xs-6 content_bl">
    <div class="create_txt">
        <p>Здравствуйте.</p>
        <p>Ваша заявка была успешно отправлена. В течение нескольких дней она будет рассмотрена и с вами обязательно свяжутся.</p>
        <p>Благодарим за использование нашего сайта.</p>
    </div>
</div>

app/views/page/create_message.html.erb
<div class="col-xs-6 content_bl">
    <div class="create_txt">
        <p>Здравствуйте.</p>
        <p>Ваше сообщение было успешно отправлено.</p>
        <p>Благодарим за использование нашего сайта.</p>
    </div>
</div>

app/views/page/help_transport.html.erb
<% set_title 'Справочная информация' %>
<div class="col-xs-6 content_bl">
    <div class="title_help_trans">
        <p>50-ТИ ТОННЫЙ КРАН ОТ УСТ РАБОТАЕТ НА РОСНЕФТЬ</p>
    </div>
    <div class="txt_help_trans">
        <p>Универсал-Спецтехника осуществила поставку 50-ти тонного крана Grove для компании Роснефть</p>
        <p>Комсомольский нефтеперерабатывающий завод пополнил свой парк техники вездеходным
            подъёмным краном от компании Grove. Тендер на поставку самоходного крана грузоподъёмностью
            50 тонн, выиграла компания Универсал-Спецтехника, лидер в области продажи спецтехники для дорожно-строительных
            и складских работ на территории РФ.</p>
        <p>Модель GMK3050 от известного мирового производителя подъёмной
            техники Manitowoc Crane Group обладает 4-х секционной стрелой с
            максимальной высотой подъёма груза до 40 м и особым трёхосном шасси,
            выполненным из высокопрочной стали. Кроме того, машина оснащена запатентованной
            гидропневматической подвеской с гидравлической блокировкой и системой автоматического выравнивания.</p>
        <p>Кран Grove GMK3050 будет работать на Комсомольском НПЗ в Хабаровском крае и был доставлен в Комсомольск-на-Амуре в
            последних числах 2014 года. В начале 2015 года специалисты Универсал-Спецтехники введут технику в эксплуатацию и
            произведут обучение персонала НПЗ (крановщиков и механиков) для грамотной работы с краном. УСТ также будет осуществлять
            гарантийное и постгарантийное обслуживание машины и поставку запасных частей при необходимости.</p>
    </div>
    <div class="img_help_trance">
        <%= image_tag 'spav_img.jpg' %>
    </div>
</div>
<div class="col-xs-3 right_bl">
    <div class="see_also">
        <div class="title_see_also">
            <p>Читайте также:</p>
        </div>
        <div class="txt_see_also">
            <p>Универсал-Спецтехника всегда держит руку на пульсе важнейших событий отрасли,
                поэтому одной из первых проголосовала за введение официального праздника
                «День экскаваторщика».</p>
        </div>
        <div class="link_reference">
            <%= link_to 'Подробнее »', page_reference_path%>
        </div>
    </div>
</div>

app/views/page/index.html.erb
<% set_title 'О компании' %>
<div class="col-xs-9 content_bl">
    <p>Добро пожаловать на сайт нашей строительной компании  «Тамбовстройсервис»!</p>
    <p>ООО «Тамбовстройсервис» работает на рынке ремонтно-строительных услуг с 2006 года.
        Наша строительная компания оказывает качественные и профессиональные услуги по всем видам
        строительно-монтажных и отделочных работ:</p>
    <ul>
        <li><span>Строительство и реконструкция зданий и сооружений.</span></li>
        <li><span>Земляные работы и благоустройство территорий.</span></li>
        <li><span>Ремонт и отделка помещений любой сложности.</span></li>
        <li><span>Монтаж технологического оборудования.</span></li>
        <li><span>Аренда спецтехники и оборудования.</span></li>
    </ul>
    <p>Индивидуальный подход к каждому клиенту обеспечивает профессиональное исполнение любого проекта и дает
        гарантию качества проведенных работ.</p>
    <p>Мы ценим ваше время, поэтому работы производятся нами в самые короткие сроки.
        У нас не бывает простоев или    сбоев в рабочем процессе, так как, производя строительные работы,
        осуществляя ремонт помещений, основным планом    действий для наших строительных бригад является
        рабочий дизайн проект помещения. Бригады четко следуют плану,    организовывают строительные работы
        таким образом, чтобы максимально эффективно использовать каждый час рабочего    времени.
        Работа над Вашим объектом осуществляется с использованием новейших строительных технологий и
        высококачественных материалов.</p>
    <ul>
        <li><span>Высокую эффективность и исполнительность компании</span></li>
        <li><span>Профессионализм и квалифицированность сотрудников</span></li>
        <li><span>Точный расчет сроков и исполнение договорных обязательств</span></li>
        <li><span>Креативные дизайнерские идеи, созданные индивидуально под клиента</span></li>
        <li><span>Технологическую грамотность на всех этапах реализации проекта</span></li>
        <li><span>Высокое качество при правильном ценообразовании</span></li>
    </ul>
</div>

app/views/page/object.html.erb
<% set_title 'Фото объектов' %>
<div class="col-xs-9 content_bl">
    <div class="row">
        <div class="col-xs-4 tech_bl">
            <%= link_to page_photo_object_cotel_path, class: 'example-image-link', data: { title: "Реконструкция котельной по адресу:  г. Тамбов,ул. Бастионная, 23" } do %>
                <%= image_tag 'img_object_4.jpg', class: 'example-image' %>
                    <p>Реконструкция котельной
                    по адресу:  г. Тамбов,
                    ул. Бастионная, 23</p>
            <% end %>
        </div>
        <div class="col-xs-4 tech_bl">
            <%= link_to page_photo_object_optica_path, class: 'example-image-link', data: {title: "Внутренние отделочные работы и устройство крыльца" } do %>
                <%= image_tag 'img_object_8.jpg', class: 'example-image' %>
                <p>Внутренние отделочные работы и устройство крыльца в торговом помещении магазина «Оптика»</p>
            <% end %>
        </div>
        <div class="col-xs-4 tech_bl">
            <%= link_to page_photo_object_sochi_path, class: 'example-image-link', data: {title: "Устройство парапета чаши фонтана Сочи" } do %>
                <%= image_tag 'img_object_12.jpg', class: 'example-image' %>
                    <p>Устройство парапета чаши фонтана "Сочи"" по адресу: г.Тамбов, Кронштадская площадь</p>
            <% end %>
        </div>
        <div class="col-xs-4 tech_bl">
            <%= link_to page_photo_object_transformer_path, class: 'example-image-link', data: {title: "Общестроительные работы на объекте: Распределительная трансформаторная подстанция 0,4 кВ с двумя трансформаторами мощностью 1000 кВа" } do %>
                <%= image_tag 'img_object_16.jpg', class: 'example-image' %>
                    <p>Cтроительные работы на объекте ...</p>
            <% end %>
        </div>
        <div class="col-xs-4 tech_bl">
            <%= link_to page_photo_object_apteki_path, class: 'example-image-link', data: {title: "Сеть аптек в Тамбовской области" } do %>
                <%= image_tag 'img_object_19.jpg', class: 'example-image' %>
                    <p>Сеть аптек в Тамбовской области"</p>
            <% end %>
        </div>
        <div class="col-xs-4 tech_bl">
            <%= link_to page_photo_object_svinkomplex_path, class: 'example-image-link', data: {title: "Свиноводческий комплекс в Рассказовском районе" } do %>
                <%= image_tag 'img_object_43.jpg', class: 'example-image' %>
                    <p>Свиноводческий комплекс в Рассказовском районе"</p>
            <% end %>
        </div>
        <div class="col-xs-4 tech_bl">
            <%= link_to page_photo_object_hlebzavod_path, class: 'example-image-link', data: {title: "Реконструкция покрытия хлебозавода в г. Рассказово" } do %>
                <%= image_tag 'img_object_46.jpg', class: 'example-image' %>
                    <p>Реконструкция покрытия хлебозавода в г. Рассказово"</p>
            <% end %>
        </div>
        <div class="col-xs-4 tech_bl">
            <%= link_to page_photo_object_agrotechnopark_path, class: 'example-image-link', data: {title: "Коттеджный поселок в агротехнопарке Мичуринский" } do %>
                <%= image_tag 'img_object_57.jpg', class: 'example-image' %>
                    <p>Коттеджный поселок в агротехнопарке "Мичуринский"</p>
            <% end %>
        </div>
        <div class="col-xs-4 tech_bl">
            <%= link_to page_photo_object_svobodnaya_path, class: 'example-image-link', data: {title: "9-этажный жилой дом по адресу г. Тамбов, ул. Свободная, 4" } do %>
                <%= image_tag 'img_object_92.jpg', class: 'example-image' %>
                    <p>9-этажный жилой дом по адресу г. Тамбов, ул. Свободная, 4</p>
            <% end %>
        </div>
    </div>
</div>

app/views/page/online_applic.html.erb
<% set_title 'Онлайн заявки' %>
<% set_body_class 'online_applic' %>
<div class="col-xs-9 content_bl">
  <p>С помощью этого раздела Вы можете вызвать нашего специалиста, который произведет необходимые
    замеры, выслушает    Ваши пожелания, сделает свои
    предложения, если таковые потребуются и в течении 1-2 дней представит сметный расчет.</p>
  <div class="row">
    <div class="col-xs-5 feedback_bl">
      <div class="feed_input">
        <%= form_tag(send_online_app_path) do %>
          <p><%= label_tag :name, 'Имя' %></p>
          <%= text_field_tag :name %>
          <br>
          <p><%= label_tag :contact, 'Контакт' %></p>
          <%= text_field_tag :contact %>
          <br>
          <p><%= label_tag :place, 'Место выполнения работ' %></p>
          <%= text_field_tag :place, nil, placeholder:'область, район, город и т.д.' %>
          <br>
          <p><%= label_tag :description, 'Описание работ' %></p>
          <%= text_field_tag :description %>
          <%= button_tag "Отправить заказ", class: "btn btn-default" %>
          <% if notice %>
            <div class="create_txt">
              <p id="notice"><span><%= notice %></span></p>
            </div>
          <% end %>
        <% end %>
        <span class="comment_feed">Все поля обязательны для заполнения!</span>
      </div>
    </div>
  </div>
</div>

app/views/page/photo_object_cotel.html.erb
<% set_title 'Реконструкция котельной по адресу: г. Тамбов, ул. Бастионная, 23' %>
<% set_body_class 'photo_object_page' %>
<content>
    <div class="container">
        <div class="row">
            <div class="col-xs-9 content_bl">
                <div class="row">
                    <div class="col-xs-12 title_object_page">
                        <p>Реконструкция котельной по адресу:  г. Тамбов, ул. Бастионная, 23</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-8">
                      <div class="row">
                        <%= images_list_for_photo_object(1..3) %>
                      </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-8">
                        <div class="row">
                          <%= images_list_for_photo_object(4..7) %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</content>

app/views/page/photo_object_hlebzavod.html.erb
<% set_title 'Реконструкция покрытия хлебозавода в г. Рассказово' %>
<% set_body_class 'photo_object_page' %>
<content>
    <div class="container">
        <div class="row">
            <div class="col-xs-9 content_bl">
                <div class="row">
                    <div class="col-xs-12 title_object_page">
                        <p>Реконструкция покрытия хлебозавода в г. Рассказово</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-8">
                        <div class="row">
                          <%= images_list_for_photo_object(46..55) %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</content>